//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""ac969357-744d-4926-9af8-9f2f3e84a31c"",
            ""actions"": [
                {
                    ""name"": ""SellTower"",
                    ""type"": ""Button"",
                    ""id"": ""c3f576e8-41d0-40a6-a8cb-910a0c985699"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""e9eb07de-3041-4cbf-a27f-9f34cb65dca4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""3c7a6d2b-fbf2-4850-ab5f-d86689e05337"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillTree"",
                    ""type"": ""Button"",
                    ""id"": ""88b8e691-9471-4bd8-94d0-c5b72bb8af6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PhysicalSpell"",
                    ""type"": ""Button"",
                    ""id"": ""a762bf98-32a6-4698-97db-a6912275dd80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MagicalSpell"",
                    ""type"": ""Button"",
                    ""id"": ""e581c5b5-fb1c-46e6-b6fa-6b3bd10003e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MechanicalSpell"",
                    ""type"": ""Button"",
                    ""id"": ""d5fd253c-2830-4253-a3c2-509cd6ff16eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ImaginarySpell"",
                    ""type"": ""Button"",
                    ""id"": ""bf0149dc-208e-4668-a952-a0ffeafacc8f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelSpell"",
                    ""type"": ""Button"",
                    ""id"": ""0eb54674-f5ae-44ed-b44a-52cbc85859c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f7eb58c1-6393-4d9d-b567-7355c5d5d34c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""SellTower"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""594546cc-86f4-4aca-ae6a-f1b8d9cc1bac"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00d2b7ec-ecc5-422f-802c-6993d7ac3b0b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4ccd0ff-27f9-4e3f-92e6-db403c352c74"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""SkillTree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2391be5a-ddd9-4bce-84eb-3a06749681ec"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""PhysicalSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb8e3080-0d07-4f09-a1b1-0b110c5d4420"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MagicalSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0035db15-f016-4f60-86af-4b175464779d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MechanicalSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5808c3b3-3013-46f8-9137-e90dfc277ed0"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ImaginarySpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5eeb5a8c-47be-476c-a3ac-c0f984716444"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CancelSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_SellTower = m_Player.FindAction("SellTower", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_Restart = m_Player.FindAction("Restart", throwIfNotFound: true);
        m_Player_SkillTree = m_Player.FindAction("SkillTree", throwIfNotFound: true);
        m_Player_PhysicalSpell = m_Player.FindAction("PhysicalSpell", throwIfNotFound: true);
        m_Player_MagicalSpell = m_Player.FindAction("MagicalSpell", throwIfNotFound: true);
        m_Player_MechanicalSpell = m_Player.FindAction("MechanicalSpell", throwIfNotFound: true);
        m_Player_ImaginarySpell = m_Player.FindAction("ImaginarySpell", throwIfNotFound: true);
        m_Player_CancelSpell = m_Player.FindAction("CancelSpell", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_SellTower;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_Restart;
    private readonly InputAction m_Player_SkillTree;
    private readonly InputAction m_Player_PhysicalSpell;
    private readonly InputAction m_Player_MagicalSpell;
    private readonly InputAction m_Player_MechanicalSpell;
    private readonly InputAction m_Player_ImaginarySpell;
    private readonly InputAction m_Player_CancelSpell;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SellTower => m_Wrapper.m_Player_SellTower;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @Restart => m_Wrapper.m_Player_Restart;
        public InputAction @SkillTree => m_Wrapper.m_Player_SkillTree;
        public InputAction @PhysicalSpell => m_Wrapper.m_Player_PhysicalSpell;
        public InputAction @MagicalSpell => m_Wrapper.m_Player_MagicalSpell;
        public InputAction @MechanicalSpell => m_Wrapper.m_Player_MechanicalSpell;
        public InputAction @ImaginarySpell => m_Wrapper.m_Player_ImaginarySpell;
        public InputAction @CancelSpell => m_Wrapper.m_Player_CancelSpell;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @SellTower.started += instance.OnSellTower;
            @SellTower.performed += instance.OnSellTower;
            @SellTower.canceled += instance.OnSellTower;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Restart.started += instance.OnRestart;
            @Restart.performed += instance.OnRestart;
            @Restart.canceled += instance.OnRestart;
            @SkillTree.started += instance.OnSkillTree;
            @SkillTree.performed += instance.OnSkillTree;
            @SkillTree.canceled += instance.OnSkillTree;
            @PhysicalSpell.started += instance.OnPhysicalSpell;
            @PhysicalSpell.performed += instance.OnPhysicalSpell;
            @PhysicalSpell.canceled += instance.OnPhysicalSpell;
            @MagicalSpell.started += instance.OnMagicalSpell;
            @MagicalSpell.performed += instance.OnMagicalSpell;
            @MagicalSpell.canceled += instance.OnMagicalSpell;
            @MechanicalSpell.started += instance.OnMechanicalSpell;
            @MechanicalSpell.performed += instance.OnMechanicalSpell;
            @MechanicalSpell.canceled += instance.OnMechanicalSpell;
            @ImaginarySpell.started += instance.OnImaginarySpell;
            @ImaginarySpell.performed += instance.OnImaginarySpell;
            @ImaginarySpell.canceled += instance.OnImaginarySpell;
            @CancelSpell.started += instance.OnCancelSpell;
            @CancelSpell.performed += instance.OnCancelSpell;
            @CancelSpell.canceled += instance.OnCancelSpell;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @SellTower.started -= instance.OnSellTower;
            @SellTower.performed -= instance.OnSellTower;
            @SellTower.canceled -= instance.OnSellTower;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Restart.started -= instance.OnRestart;
            @Restart.performed -= instance.OnRestart;
            @Restart.canceled -= instance.OnRestart;
            @SkillTree.started -= instance.OnSkillTree;
            @SkillTree.performed -= instance.OnSkillTree;
            @SkillTree.canceled -= instance.OnSkillTree;
            @PhysicalSpell.started -= instance.OnPhysicalSpell;
            @PhysicalSpell.performed -= instance.OnPhysicalSpell;
            @PhysicalSpell.canceled -= instance.OnPhysicalSpell;
            @MagicalSpell.started -= instance.OnMagicalSpell;
            @MagicalSpell.performed -= instance.OnMagicalSpell;
            @MagicalSpell.canceled -= instance.OnMagicalSpell;
            @MechanicalSpell.started -= instance.OnMechanicalSpell;
            @MechanicalSpell.performed -= instance.OnMechanicalSpell;
            @MechanicalSpell.canceled -= instance.OnMechanicalSpell;
            @ImaginarySpell.started -= instance.OnImaginarySpell;
            @ImaginarySpell.performed -= instance.OnImaginarySpell;
            @ImaginarySpell.canceled -= instance.OnImaginarySpell;
            @CancelSpell.started -= instance.OnCancelSpell;
            @CancelSpell.performed -= instance.OnCancelSpell;
            @CancelSpell.canceled -= instance.OnCancelSpell;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnSellTower(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnRestart(InputAction.CallbackContext context);
        void OnSkillTree(InputAction.CallbackContext context);
        void OnPhysicalSpell(InputAction.CallbackContext context);
        void OnMagicalSpell(InputAction.CallbackContext context);
        void OnMechanicalSpell(InputAction.CallbackContext context);
        void OnImaginarySpell(InputAction.CallbackContext context);
        void OnCancelSpell(InputAction.CallbackContext context);
    }
}
